### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by weijia-cheng** [jlund/ivy-compton-burnett_pastors-and-masters#1]
# Semantics

- [x] Rerunning `se build-toc .` updates some semantics in the table of contents.o
- [x] Running `se build --check-only .` indicates that the `z3998:roman` should be removed from the `title` element in each chapter file.

# Meta

- [x] 5b9b39a1b73ff06682337b4c43a988fff02a7954: We usually consider italics changes like this to be semantics, which is to say, not editorial. Let’s remove the [Editorial] tag in a rebase.
- [x] 3a128402bf1c7932fa2546dfb51e8d63feb549c8: This is also a semantics change that doesn’t need to be marked as [Editorial]. Also, this should probably be a `z3998:phoneme`, not a `z3998:grapheme`, since it is referring to the sound and not the written letter.

**Comment by jlund** [comment]
Thanks, @weijia-cheng!

* Rerunning se build-toc . updates some semantics in the table of contents.
  * Rebased/removed in https://github.com/jlund/ivy-compton-burnett_pastors-and-masters/commit/a6c930eaa343aec14ace1e40186486281cff4100
* Running se build --check-only . indicates that the z3998:roman should be removed from the title element in each chapter file.
  * Fixed in https://github.com/jlund/ivy-compton-burnett_pastors-and-masters/commit/7e5aae83cb4c72e4d08f7d48f86226907c059cb5
* https://github.com/jlund/ivy-compton-burnett_pastors-and-masters/commit/5b9b39a1b73ff06682337b4c43a988fff02a7954: We usually consider italics changes like this to be semantics, which is to say, not editorial. Let’s remove the [Editorial] tag in a rebase.
  * Fixed in https://github.com/jlund/ivy-compton-burnett_pastors-and-masters/commit/5474bec0a3bde9c2d4ecf51ef4e6bff5f6440d28
* https://github.com/jlund/ivy-compton-burnett_pastors-and-masters/commit/3a128402bf1c7932fa2546dfb51e8d63feb549c8: This is also a semantics change that doesn’t need to be marked as [Editorial]. Also, this should probably be a z3998:phoneme, not a z3998:grapheme, since it is referring to the sound and not the written letter.
  * Fixed in https://github.com/jlund/ivy-compton-burnett_pastors-and-masters/commit/f2c65df2ae08756ee2154216c1567e837e04f97f

I maintained all of the original commits in the `pre-review` branch, so you can see a full diff with `git diff pre-review master` after pulling the latest changes.
